name: Build EDGY Hacks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ${{ github.workspace }}/theos
          curl -L https://github.com/theos/sdks/archive/master.zip -o sdks.zip
          unzip -q sdks.zip
          mkdir -p ${{ github.workspace }}/theos/sdks
          mv -f sdks-master/* ${{ github.workspace }}/theos/sdks/
          rm -rf sdks-master sdks.zip

      - name: Build Tweak
        run: |
          cd tweak
          make package FINALPACKAGE=1 THEOS=$THEOS
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EdgyHacks-Build
          path: |
            tweak/packages/*.deb
            tweak/.theos/obj/**/*.dylib
