name: Build EDGY Hacks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-dir: 'theos'
          theos-src: 'https://github.com/theos/theos'
          theos-sdks: 'https://github.com/theos/sdks'

      - name: Build Tweak
        run: |
          cd tweak
          make package FINALPACKAGE=1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: EdgyHacks-Build
          path: |
            tweak/packages/*.deb
            tweak/.theos/obj/**/*.dylib
